#host parameter is mandatory parameter. fully qualified domain name
host: mymachine.pnl.gov

# mandatory. certificate data used to create root ca certificate. Each volttron
# instance must have unique common-name for root ca certificate
certificate-data:
  country: 'US'
  state: 'Washington'
  location: 'Richland'
  organization: 'PNNL'
  organization-unit: 'VOLTTRON Team'
  common-name: 'volttron_instance1_root_ca'
#
# optional parameters for single instance setup
#
virtual-host: 'volttron1' #defaults to volttron

# use the below four port variables if using custom rabbitmq ports
# defaults to 5672
amqp-port: '5672'

# defaults to 5671
amqp-port-ssl: '5671'

# defaults to 15672
mgmt-port: '15672'
# defaults to 15671
mgmt-port-ssl: '15671'

# defaults to true
ssl: 'true'

# defaults to user_home/rabbitmq_server/rabbbitmq_server-3.7.7
rmq-home: "/home/volttron/rabbitmq_server/rabbitmq_server-3.7.7"


# Mandatory parameters for federation setup
federation-upstream:
  rabbit-4:
    port: '5671'
    virtual-host: volttron4
  rabbit-5:
    port: '5671'
    virtual-host: volttron5
  rabbit-6:
    port: '5671'
    virtual-host: volttron6
  rabbit-7:
    port: '5671'
    virtual-host: volttron7

# Mandatory parameters for shovel setup
shovel:
  rabbit-3:
    port: '5671'
    virtual-host: volttron3
    pubsub-topics:
    - devices
    - heartbeat
    rpc-agent-identities:
    - schedule_example
